# Run tests using the beta Rust compiler

name: Beta Rust

on:
  workflow_call:
    inputs:
      tests:
        description: "Reusable workflow of the tests to be executed using the beta compiler"
        type: string
        required: true

env:
  IROH_FORCE_STAGING_RELAYS: "1"

jobs:
  tests:
    uses: "${{ inputs.tests }}"
    with:
      rust-version: beta
  notify:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract test results
        run: |
          printf '${{ toJSON(needs) }}\n'
          result=$(echo '${{ toJSON(needs) }}' | jq -r .tests.result)
          echo TESTS_RESULT=$result
          echo "TESTS_RESULT=$result" >>"$GITHUB_ENV"
      - name: Notify discord on failure
        uses: n0-computer/discord-webhook-notify@v1
        if: ${{ env.TESTS_RESULT == 'failure' }}
        with:
          text: "Beta Rust in **${{ github.repository }}**:"
          severity: error
          details: |
            Rustc beta tests failed
            See https://github.com/${{ github.repository }}/actions/worklows/${{ github.workflow }}
          webhookUrl: ${{ secrets.DISCORD_N0_GITHUB_CHANNEL_WEBHOOK_URL }}

